# default configuration
baseURL = "http://examplesite.com"
languageCode = "pt-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Sobre mim_"

# css plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/slick/slick.css"
[[params.plugins.css]]
link = "/plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#41228e"

# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format